# Generated by Django 4.2.4 on 2023-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0003_alter_itmeprice_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmeprice',
            name='item_title',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
