# Generated by Django 4.2.4 on 2023-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0004_alter_itmeprice_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmeprice',
            name='item_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itmeprice',
            name='link',
            field=models.URLField(),
        ),
    ]
