# Generated by Django 4.2.4 on 2023-08-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0006_alter_itmeprice_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itmeprice',
            old_name='link',
            new_name='url',
        ),
    ]
