# Generated by Django 4.2.4 on 2023-08-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0007_rename_link_itmeprice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmeprice',
            name='item_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itmeprice',
            name='old_price',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itmeprice',
            name='price_difference',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
