# Generated by Django 4.2.4 on 2023-08-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0008_alter_itmeprice_item_title_alter_itmeprice_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmeprice',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itmeprice',
            name='old_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itmeprice',
            name='price_difference',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
