# Generated by Django 4.2.4 on 2023-08-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0011_alter_itmeprice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itmeprice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
