# Generated by Django 4.2.4 on 2023-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0012_itmeprice_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itmeprice',
            options={'ordering': ('price_difference', '-created')},
        ),
        migrations.AlterField(
            model_name='itmeprice',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
